version: '3.5'
services:
  zabbix-mysql:
    image: mysql:8.0
    container_name: mysql-sever
    command:
    - --character-set-server=utf8
    - --collation-server=utf8_bin
    - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: Integ123
      MYSQL_ROOT_PASSWORD: Integ123
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.4
  zabbix-server:
     image: zabbix/zabbix-server-mysql:alpine-5.0-latest
     container_name: zabbix-server
     environment:
       DB_SERVER_HOST: zabbix-mysql
       MYSQL_DATABASE: zabbix
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: Integ123
       MYSQL_ROOT_PASSWORD: Integ123
     ports:
       - '10051:10051' 
     volumes:
       - snmptraps:/var/lib/zabbix/snmptraps
       - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
     networks:
       zabbix-net:
         ipv4_address: 172.20.240.5
    
  zabbix-web:
     image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
     container_name: zabbix-web
     environment:
       DB_SERVER_HOST: zabbix-mysql
       MYSQL_DATABASE: zabbix
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: Integ123
       MYSQL_ROOT_PASSWORD: Integ123
       ZBX_SERVER_HOST: zabbix-server
     ports:
        - '443:8443'
        - '81:8080'
     volumes:  
       - /etc/ssl/nginx:/etc/ssl/nginx:ro
     networks:
       zabbix-net:
         ipv4_address: 172.20.240.6
  
  zabbix-snmptraps:
     image: zabbix/zabbix-snmptraps:alpine-5.0-latest
     container_name: zabbix-snmptraps
     ports:
       - '162:1162' 
     volumes:
       - snmptraps:/var/lib/zabbix/snmptraps
       - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro 
     networks:
      zabbix-net:
        ipv4_address: 172.20.240.7

  zabbix-agent:
     image: zabbix/zabbix-agent:alpine-5.0-latest
     container_name: zabbix-agent
     environment:
       ZBX_SERVER_HOST: zabbix-server
     networks:
       zabbix-net:
         ipv4_address: 172.20.240.8
 
networks:
  zabbix-net:
    driver: bridge
    ipam:
      driver: default  
      config:
      - subnet: 172.20.0.0/16 
  
volumes:
  snmptraps:
